### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by timveranneman** [jonhattan/puppet-drush#13]
Hello,

this module requires :
puppetlabs/stdlib (>=4.2.2 <5.0.0)
puppetlabs/concat (>=1.1.0 <2.0.0)
could it work with?
puppetlabs-concat (v5.3.0)
puppetlabs-stdlib (v5.2.0) 
If so can you adjust the metadata.json?

kind regards,
Tim

**Comment by jonhattan** [comment]
Fixed time ago in https://github.com/jonhattan/puppet-drush/commit/a5f693187d2ff69c98962fc921c59ed25820a9b2
